model = "gpt-5.5"
model_reasoning_effort = "xhigh"
notify = ["/Users/stan/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]
service_tier = "default"

[projects."/Users/stan/Git/dot-agents"]
trust_level = "trusted"

[projects."/Users/stan/Git/research-agent"]
trust_level = "trusted"

[plugins."github@openai-curated"]
enabled = true

[plugins."google-drive@openai-curated"]
enabled = true

[plugins."life-science-research@openai-curated"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[marketplaces.openai-bundled]
last_updated = "2026-06-25T10:30:40Z"
source_type = "local"
source = "/Users/stan/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-06-24T06:56:04Z"
source_type = "local"
source = "/Users/stan/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[tui.model_availability_nux]
"gpt-5.5" = 4

[desktop]
ambient-suggestions-enabled = false
selected-avatar-id = "custom:codec"
conversationDetailMode = "STEPS_COMMANDS"
appearanceTheme = "dark"

[features]
hooks = true
js_repl = false
memories = true

[mcp_servers.node_repl]
args = []
command = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/Codex.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/stan/.codex"
CODEX_HOME = "/Users/stan/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "5504c0782b5c86b7dd08314045b9843e973a230e1be8f7e2e0ba3716fc63c55e"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.616.81150"
CODEX_CLI_PATH = "/Applications/Codex.app/Contents/Resources/codex"

[memories]
generate_memories = true
use_memories = true

[hooks.state]
